### ISSUE TITLE
Switch to YAML config file

### ISSUE THREAD

**Issue by blackstream-x** [blackstream-x/file-manager-integration#9]

**Comment by blackstream-x** [comment]
Example:

```yaml
name: Menu entry display
description: Example handling image and video files
relative path: executable.py
mime types:
  - image/*
  - video/*
translations:
  de:
    name: Menüeintrag
    description: Beispiel eines Skripts, das etwas mit Bildern und Videos macht
applies to:
  # used by Thunar, but could maybe also reflect back to mime types?
  directories: false
  audio-files: false
  image-files: true
  other-files: false
  text-files: false
  video-files: true
```
